### PR TITLE
Fix/rss limit value error 2.3.x

### LINKED ISSUE #138: RSS product limit default value not set on install
**Bug description**
On a fresh install, saving any setting besides RSS will pop up this error 

> RSS product limit value must be between 1 and 250

**Steps for reproducing**

1. Install module
2. Go to module settings
3. Validate credentials.
4. Set 'Enable Smaily Module' to false.

**Expected behavior**
'Enable Smaily Module' setting is set to disabled and saving settings is successful.

**Actual behavior**
Error will be displayed that RSS product limit value is not what the module is expecting.

**Screenshots**
image

**OpenCart version**
OpenCart 3.0.x
OpenCart 2.3.x
OpenCart 2.2.x

**Module version**
1.4.0

**Additional context**

### PR DESCRIPTION
**Pull request by TomAbel**
closes #138

### CODE REVIEW

File: upload/admin/controller/extension/module/smaily_for_opencart.php [hunk 1]
```diff
@@ -456,10 +456,15 @@ public function index() {
...
+        if (! empty($this->request->post['smaily_for_opencart_rss_limit'])) {
             $data['rss_limit'] = $this->request->post['smaily_for_opencart_rss_limit'];
         } else {
-            $data['rss_limit'] = $this->config->get('smaily_for_opencart_rss_limit');
+            if(! empty($this->config->get('smaily_for_opencart_rss_limit'))) {
+                $data['rss_limit'] = $this->config->get('smaily_for_opencart_rss_limit');
+            } else {
+                $data['rss_limit'] = 50;
+            }
+
```
Comment (kaittodesk) [inline upload/admin/controller/extension/module/smaily_for_opencart.php:467]: You can write this using following pattern:

```php
if (...) {
  // ...
} else if (...) {
  // ...
} else {
  // ...
}
```

This way you will reduce unnecessary indentation.

**Review by kaittodesk — CHANGES_REQUESTED** [review]

File: upload/admin/controller/extension/module/smaily_for_opencart.php (hunk 1 above)
Comment (TomAbel) [reply upload/admin/controller/extension/module/smaily_for_opencart.php]: added 
1d67064

**Review by kaittodesk — APPROVED** [review]
