### PR TITLE
Move cURL calls to a seperate Request library

### LINKED ISSUE #124: Abandoned cart CRON can get stuck
**Bug description**
Customer, with an email address that Smaily does not recognize as valid, can cause abandoned cart CRON to get stuck trying to resubmit invalid data to Smaily API until an abandoned cart with a valid email address is added.

**Steps for reproducing**

As an admin:
1. Go to your stores admin panel;
2. Enable and connect module with Smaily;
3. Configure Abandoned Cart functionality and CRON job;

As a anonymous user:
1. Go to your store;
2. Register a customer with invalid email address (like customer@smaily.sandbox);
3. Login to registered customer's account;
4. Add products to your shopping cart;
5. Wait for the abandoned cart CRON to run;

**Expected behavior**
CRON discards invalid email address and does not try to resend invalid data to Smaily API until an abandoned cart with valid email address is added.

**Actual behavior**
CRON tries to resend abandoned cart request to Smaily API on every cycle until an abandoned cart with valid email address is added.

**Versions**
OpenCart: 3.0.3.1
Smaily For Opencart: 1.3.2

Since 1.4.0 did not make any changes to Abandoned Cart CRON or its helpers, then it is safe to assume that 1.4.0 does not fix it.

### PR DESCRIPTION
**Pull request by TomAbel**
related to and fixes #124

refactors and simplifies code used for making requests against Smaily's API.
OpenCart 2.3.x

### CODE REVIEW

File: upload/admin/model/extension/smailyforopencart/admin.php [hunk 1]
```diff
@@ -31,82 +31,59 @@ public function uninstall() {
...
-                $this->log->write($api_call['message']);
-            }
+    public function normalizeSubdomain($subdomain) {
+        // First, try to parse as full URL.
+        // If that fails, try to parse as subdomain.sendsmaily.net.
+        // Last resort clean up subdomain and pass as is.
+        if (filter_var($subdomain, FILTER_VALIDATE_URL)) {
+        $url = parse_url($subdomain);
+        $parts = explode('.', $url['host']);
+        $subdomain = (count($parts) >= 3) ? $parts[0] : '';
```
Comment (kaittodesk) [inline upload/admin/model/extension/smailyforopencart/admin.php:48]: Formatting: indentation.

File: upload/admin/model/extension/smailyforopencart/admin.php [hunk 2]
```diff
@@ -31,82 +31,59 @@ public function uninstall() {
...
-            // GET.
-            } else {
-                $response = $api_call;
-            }
-        } else {
-            // Log error.
-            $this->log->write('Error in smaily api call with code: ' . $http_code);
+        elseif (preg_match('/^[^\.]+\.sendsmaily\.net$/', $subdomain)) {
+        $parts = explode('.', $subdomain);
+        $subdomain = $parts[0];
```
Comment (kaittodesk) [inline upload/admin/model/extension/smailyforopencart/admin.php:52]: Formatting: indentation.

**Review by kaittodesk — CHANGES_REQUESTED** [review]

File: upload/admin/model/extension/smailyforopencart/admin.php (hunk 2 above)
Comment (TomAbel) [reply upload/admin/model/extension/smailyforopencart/admin.php]: Fixed with 8c27561
added `<rule ref="Generic.WhiteSpace.ScopeIndent">` to my ruleset as it didn't light up

**Review by kaittodesk — APPROVED** [review]

**Review by kaittodesk — APPROVED** [review]
